[package]
edition = "2021"
name = "ray-tracing"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive-new = "0.5"
easy-cast = "0.5"
indicatif = "0.17"
itertools = "0.11"
num = "0.4"
